pipelines:
  default:
    - step:
        name: "PHP 7.1"
        image: php:7.1.1
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpcs -p --ignore=./assets/*,./node_modules/*,./src/*,./vendor/* ./ --standard=PHPCompatibility --runtime-set testVersion 5.6
          - vendor/bin/phpcs -p --ignore=./assets/*,./node_modules/*,./src/*,./vendor/* ./ --standard=PHPCompatibility --runtime-set testVersion 7.0
          - vendor/bin/phpcs -p --ignore=./assets/*,./node_modules/*,./src/*,./vendor/* ./ --standard=PHPCompatibility --runtime-set testVersion 7.1
    - step:
        name: "PHP 7.2"
        image: php:7.2.14
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpcs -p --ignore=./assets/*,./node_modules/*,./src/*,./vendor/* ./ --standard=PHPCompatibility --runtime-set testVersion 7.2
    - step:
        name: "PHP 7.3"
        image: php:7.3.1
        script:
          - apt-get update && apt-get install -y unzip
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpcs -p --ignore=./assets/*,./node_modules/*,./src/*,./vendor/* ./ --standard=PHPCompatibility --runtime-set testVersion 7.3
